### ISSUE TITLE
你好，请问什么时候可以提供Jcenter的依赖下载

### ISSUE THREAD

**Issue by sunshinehu** [iReaderAndroid/X2C#17]
这个库实在是很有想法，为作者点赞！依赖工程不是很方便，提供Jcenter接入就更好了，另外该方案请问有上线使用了吗，有没有遇到什么问题

**Comment by chengweidev** [comment]
jcenter已经在上传审核中，因为方便大家查看修改源码，我们现在直接放出代码了。我们现在已经上线使用了，能比较明显的提升性能，问题在README里也提到过，不支持merge标签和系统style
