### ISSUE TITLE
app\src\main\res\layout\null.xml (系统找不到指定的文件。)

### ISSUE THREAD

**Issue by Anzhi-Meiying** [iReaderAndroid/X2C#2]
如题，我想直接得到java代码

**Comment by jimor1234567** [comment]
在app/build/generated/source/apt/debug/的子文件夹下。

**Comment by Anzhi-Meiying** [comment]
@jimor1234567 再打扰一下，请问 windows 无法使用吗，报错了

**Comment by chengweidev** [comment]
@Anzhi-Meiying 能将错误日志贴出来吗？

**Comment by Anzhi-Meiying** [comment]
@chengweidev java.io.FileNotFoundException: D:\Android\Studio\Projects\Preview\app\src\main\res\layout\null.xml (系统找不到指定的文件。)

`警告: 类型 '[bb]' 的文件未关闭; 将不针对这些类型进行注释处理
D:\Android\Studio\Projects\PureQQPreview\app\build\generated\source\apt\debug\com\zhangyue\we\x2c\X2C_127.java:18: 错误: 不兼容的类型: <空值>无法转换为int
        	case null:
        	     ^
D:\Android\Studio\Projects\PureQQPreview\app\build\generated\source\apt\debug\com\zhangyue\we\x2c\X2C_127.java:19: 错误: 找不到符号
        		view = new X2C_127_Null().createView(context,null);
        		           ^
  符号:   类 X2C_127_Null
  位置: 类 X2C_127`

**Comment by Anzhi-Meiying** [comment]
@chengweidev 你好，请问怎么解决
我在fragment添加了注解的，R.layout.activity_main
但是运行他提示

> java.io.FileNotFoundException: D:\Android\Studio\Projects\Preview\app\src\main\res\layout\null.xml (系统找不到指定的文件。)

**Comment by Anzhi-Meiying** [comment]
@jimor1234567 @chengweidev 已找到解决办法，将Gradle版本改成

> com.android.tools.build:gradle:3.1.4

即可，之前是3.3.0就编译失败，请问X2C到时候会支持新版本的Gradle吗

**Comment by chengweidev** [comment]
最新的gradle版本我们会适配
