### ISSUE TITLE
gradle:3.3.0-alpha06 问题

### ISSUE THREAD

**Issue by Anzhi-Meiying** [iReaderAndroid/X2C#21]
在Gradle 3.3.0版本使用 X2C 会报如下错误，3.1.4以下则无此问题，会适配新版吗，因为项目中有一些需要3.3.0的gradle的东西，所以无法降级

![eafm1ai91p241ta11ow2vw](https://user-images.githubusercontent.com/13428030/44850486-e78edb00-ac8f-11e8-85a6-6f8a3597ac66.png)
![ce me0 mdk hnxkpn u4s](https://user-images.githubusercontent.com/13428030/44850487-e8277180-ac8f-11e8-9e02-66cd0833d5bd.png)

**Comment by chengweidev** [comment]
@Anzhi-Meiying 已经修复，请更新代码

**Comment by Anzhi-Meiying** [comment]
@chengweidev 好的收到
