### ISSUE TITLE
其他目录的layout怎么办呢？比如说 layout-land 中的

### ISSUE THREAD

**Issue by kaiyangjia** [iReaderAndroid/X2C#22]
1. apt 模块中获取layout的路径是写死的 main/src/res/layout 下面，那其他目录下的layout怎么处理？
2. 然后是，如果res的目录是自定义的呢，即在gradle文件中配置的目录？并不是在 main/src/res/layout 下面的呢？

针对这个问题，是不是可以在X2C_config.xml 中添加一个配置项来解决呢？如果可以的话我可以改一下之后发PR。

**Comment by jimor1234567** [comment]
你可以帮忙修改一下，然后发一个PR。

**Comment by chengweidev** [comment]
@kaiyangjia 已经支持  layout，layout-land,layout-v23等
