### ISSUE TITLE
设置默认构造器无意义

### ISSUE THREAD

**Issue by dkzwm** [iReaderAndroid/X2C#5]
@chengweidev 最新提交的代码中删除了我提交的部分，替代的代码回溯到了老的代码逻辑，填充默认构造器的方式浪费资源没什么必要，
```    private static View getView(Context context, int layoutId) {
        IViewCreator creator = null;
        //此次已经判断了是否构造过，不会多次构造
        if (sSparseArray.indexOfKey(layoutId) >= 0) {
            creator = sSparseArray.get(layoutId);
        } else {
            try {
                creator = (IViewCreator) context.getClassLoader()
                        .loadClass("com.zhangyue.we.x2c.X2C_" + layoutId).newInstance();
            } catch (Exception ignored) {//
            }
           //SparseArray的value可以为null
            sSparseArray.put(layoutId, creator);
        }
        return creator == null ? null : creator.createView(context, layoutId);
    }
```
另外generateGroupId本意是缩短类名长度，但通过位运算后可能导致ID重复，所以并有没必要。

**Comment by chengweidev** [comment]
是有意义的，X2C是通过map类去加载view，这里的creator实际上是map类，
generateGroupId 是分组名称，因为我们需要满足插件也能使用，generateGroupId对应每个插件的map

**Comment by dkzwm** [comment]
@chengweidev  我想表达的意思是IViewCreator不会重复实例化，代码保证了只会实例化一次，如果实例化失败说明Java类文件不存在下次调用直接跳过使用系统API构造Xml, `generateGroupId`有分组名称的功能，我想表达的意思是位运算并不能保证Id不重复，极端情况下可能导致Map里的Key重复导致覆盖,Android的资源Id是保证了Id不可能重复的，直接使用Id更可靠。

**Comment by dkzwm** [comment]
我使用`SparseArray`来存储`IViewCreator `,目的一是`SparseArray`有更优秀的内存占用优化，目的二是`SparseArray`支持Value为null,这样做就可以不用实例化默认构造器，直接先判断是否存在Key，存在说明实例化过，如果为空直接跳过。

**Comment by chengweidev** [comment]
@dkzwm  SparseArray是可以优化内存，这点我赞同，所以保留了你的提交。因为入参是 资源id，如果传进来的资源id没有对应的java类，就会多次走到else分支里，导致多次调用反射，影响性能。而原先的设计是通过map统一去new对应的类（只有map本身是反射生成），性能会更好，这样设计的宗旨是尽量减少反射的次数

**Comment by dkzwm** [comment]
@chengweidev SparseArray的value可以为null,所以put进去资源Id为Key, null为value是有效的，也就在indexOfKey(layoutId)时key存在但value不存在的情况是存在的，所以不会走再次实例化的过程。

**Comment by chengweidev** [comment]
@dkzwm  嗯，你说的是正确的
