### ISSUE TITLE
支持databinding吗？

### ISSUE THREAD

**Issue by JakeWoki** [iReaderAndroid/X2C#6]
或者butterknife

**Comment by chengweidev** [comment]
现在还不支持，我们会在下版完善

**Comment by chengweidev** [comment]
@JakeWoki  已经支持DataBinding和butterknife  ，和butterknife  不需要做任何改动。DataBinding需要将原先的 DataBindingUtil.setContentView(this, R.layout.activity) 换成DataBindingX2C.setContentView(this, R.layout.activity);

**Comment by chengweidev** [comment]
@JakeWoki  已经支持DataBinding和butterknife  ，和butterknife  不需要做任何改动。DataBinding需要将原先的 DataBindingUtil.setContentView(this, R.layout.activity) 换成DataBindingX2C.setContentView(this, R.layout.activity);

**Comment by JakeWoki** [comment]
辛苦了，下周试试
